### PR TITLE
General Clean / Improvements

### PR DESCRIPTION
**Pull request by darbyjack**

### CODE REVIEW

**Comment by darbyjack** [comment]
This should be good to pull. I cleaned up a few things and it looks to run fine.

**Comment by delta2force** [comment]
Thank you!

**Comment by delta2force** [comment]
Also i have just noticed who you are! Thank you so much for the things you have done for the spigot community!

**Comment by darbyjack** [comment]
Glad I could help! I'm a fellow Reddit lurker and saw something I could contribute to!

**Pull request merged**
